# Generated by Django 5.0 on 2023-12-22 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Conteúdo do texto')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
        ),
    ]
