# Generated by Django 5.0 on 2023-12-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
    ]
